### PR TITLE
add signed vs unsigned number checks and add text validations to the …

### PR DESCRIPTION
**Pull request by kotobusdriver**
…backend

### CODE REVIEW

**Comment by altanborali16** [comment]
We are also doing validation on frontend, but I could not understand signed and unsigned datatypes can you inform me about it

**Comment by kotobusdriver** [comment]
Signed are the ones that accept both negative and positive numbers, unsigned accept only the positive ones

**Comment by altanborali16** [comment]
Okay I will merge it as soon as possible because when I merge it we need to recreate database, which will end up with loosing current data.

**Comment by altanborali16** [comment]
image
image
image

Looks like there is no problem

**Pull request merged**
