### PR TITLE
Feature/yana 165 add remove members to community

### PR DESCRIPTION
**Pull request by kotobusdriver**
The community Creator is now able to assign Admin role to community members. Creator has the same permission set as Admins. Admins can kick users out of the community.

### CODE REVIEW

**Comment by altanborali16** [comment]
If a kicked user has some post, comment, reply or vote, do they also deleted, because yesterday I found out that if community has an entry from a nonsubscriber we have an error. I will test add ADMIN and kick user tonight and be sure about it.

**Comment by altanborali16** [comment]
If it is a problem we can go with ADMIN rights as create template

**Comment by kotobusdriver** [comment]
> If a kicked user has some post, comment, reply or vote, do they also deleted, because yesterday I found out that if community has an entry from a nonsubscriber we have an error. I will test add ADMIN and kick user tonight and be sure about it.

No; for now, post, comment, reply and vote left by the kicked-out user remain in the community.

**Comment by altanborali16** [comment]
I am accepting pull request, some parts or full of it will be used. Also for not to have merge conflicts.

**Pull request merged**
